CREATE TABLE user (
	user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	username text NOT NULL,	
	lastname text NOT NULL,	
	email text NOT NULL,	
	role text NOT NULL,
   
	CONSTRAINT user_pk PRIMARY KEY (user_id)	
);